version: '3'

services:
  bayard:
    container_name: bayard
    image: mosuka/bayard:latest
    entrypoint: bayard
    command:
      - '--bind-address=0.0.0.0:2000'
      - '--grpc-address=0.0.0.0:5000'
      - '--http-address=0.0.0.0:8000'
      - '--data-directory=/tmp/bayard'
      - '--schema-file=/etc/bayard/schema.json'
    ports:
      - "2000:2000"
      - "5000:5000"
      - "8000:8000"
