// This file is generated by rust-protobuf 2.8.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `indexrpcpb.proto`

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_8_0;

#[derive(PartialEq,Clone,Default)]
pub struct IndexReq {
    // message fields
    pub client_id: u64,
    pub seq: u64,
    pub req_type: ReqType,
    pub peer_id: u64,
    pub peer_addr: ::std::string::String,
    pub key: ::std::string::String,
    pub value: ::std::string::String,
    pub query: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a IndexReq {
    fn default() -> &'a IndexReq {
        <IndexReq as ::protobuf::Message>::default_instance()
    }
}

impl IndexReq {
    pub fn new() -> IndexReq {
        ::std::default::Default::default()
    }

    // uint64 client_id = 1;


    pub fn get_client_id(&self) -> u64 {
        self.client_id
    }
    pub fn clear_client_id(&mut self) {
        self.client_id = 0;
    }

    // Param is passed by value, moved
    pub fn set_client_id(&mut self, v: u64) {
        self.client_id = v;
    }

    // uint64 seq = 2;


    pub fn get_seq(&self) -> u64 {
        self.seq
    }
    pub fn clear_seq(&mut self) {
        self.seq = 0;
    }

    // Param is passed by value, moved
    pub fn set_seq(&mut self, v: u64) {
        self.seq = v;
    }

    // .indexrpcpb.ReqType req_type = 3;


    pub fn get_req_type(&self) -> ReqType {
        self.req_type
    }
    pub fn clear_req_type(&mut self) {
        self.req_type = ReqType::Get;
    }

    // Param is passed by value, moved
    pub fn set_req_type(&mut self, v: ReqType) {
        self.req_type = v;
    }

    // uint64 peer_id = 4;


    pub fn get_peer_id(&self) -> u64 {
        self.peer_id
    }
    pub fn clear_peer_id(&mut self) {
        self.peer_id = 0;
    }

    // Param is passed by value, moved
    pub fn set_peer_id(&mut self, v: u64) {
        self.peer_id = v;
    }

    // string peer_addr = 5;


    pub fn get_peer_addr(&self) -> &str {
        &self.peer_addr
    }
    pub fn clear_peer_addr(&mut self) {
        self.peer_addr.clear();
    }

    // Param is passed by value, moved
    pub fn set_peer_addr(&mut self, v: ::std::string::String) {
        self.peer_addr = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_peer_addr(&mut self) -> &mut ::std::string::String {
        &mut self.peer_addr
    }

    // Take field
    pub fn take_peer_addr(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.peer_addr, ::std::string::String::new())
    }

    // string key = 6;


    pub fn get_key(&self) -> &str {
        &self.key
    }
    pub fn clear_key(&mut self) {
        self.key.clear();
    }

    // Param is passed by value, moved
    pub fn set_key(&mut self, v: ::std::string::String) {
        self.key = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_key(&mut self) -> &mut ::std::string::String {
        &mut self.key
    }

    // Take field
    pub fn take_key(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.key, ::std::string::String::new())
    }

    // string value = 7;


    pub fn get_value(&self) -> &str {
        &self.value
    }
    pub fn clear_value(&mut self) {
        self.value.clear();
    }

    // Param is passed by value, moved
    pub fn set_value(&mut self, v: ::std::string::String) {
        self.value = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_value(&mut self) -> &mut ::std::string::String {
        &mut self.value
    }

    // Take field
    pub fn take_value(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.value, ::std::string::String::new())
    }

    // string query = 8;


    pub fn get_query(&self) -> &str {
        &self.query
    }
    pub fn clear_query(&mut self) {
        self.query.clear();
    }

    // Param is passed by value, moved
    pub fn set_query(&mut self, v: ::std::string::String) {
        self.query = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_query(&mut self) -> &mut ::std::string::String {
        &mut self.query
    }

    // Take field
    pub fn take_query(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.query, ::std::string::String::new())
    }
}

impl ::protobuf::Message for IndexReq {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.client_id = tmp;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.seq = tmp;
                },
                3 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.req_type, 3, &mut self.unknown_fields)?
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.peer_id = tmp;
                },
                5 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.peer_addr)?;
                },
                6 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.key)?;
                },
                7 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.value)?;
                },
                8 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.query)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.client_id != 0 {
            my_size += ::protobuf::rt::value_size(1, self.client_id, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.seq != 0 {
            my_size += ::protobuf::rt::value_size(2, self.seq, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.req_type != ReqType::Get {
            my_size += ::protobuf::rt::enum_size(3, self.req_type);
        }
        if self.peer_id != 0 {
            my_size += ::protobuf::rt::value_size(4, self.peer_id, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.peer_addr.is_empty() {
            my_size += ::protobuf::rt::string_size(5, &self.peer_addr);
        }
        if !self.key.is_empty() {
            my_size += ::protobuf::rt::string_size(6, &self.key);
        }
        if !self.value.is_empty() {
            my_size += ::protobuf::rt::string_size(7, &self.value);
        }
        if !self.query.is_empty() {
            my_size += ::protobuf::rt::string_size(8, &self.query);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.client_id != 0 {
            os.write_uint64(1, self.client_id)?;
        }
        if self.seq != 0 {
            os.write_uint64(2, self.seq)?;
        }
        if self.req_type != ReqType::Get {
            os.write_enum(3, self.req_type.value())?;
        }
        if self.peer_id != 0 {
            os.write_uint64(4, self.peer_id)?;
        }
        if !self.peer_addr.is_empty() {
            os.write_string(5, &self.peer_addr)?;
        }
        if !self.key.is_empty() {
            os.write_string(6, &self.key)?;
        }
        if !self.value.is_empty() {
            os.write_string(7, &self.value)?;
        }
        if !self.query.is_empty() {
            os.write_string(8, &self.query)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> IndexReq {
        IndexReq::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "client_id",
                    |m: &IndexReq| { &m.client_id },
                    |m: &mut IndexReq| { &mut m.client_id },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "seq",
                    |m: &IndexReq| { &m.seq },
                    |m: &mut IndexReq| { &mut m.seq },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<ReqType>>(
                    "req_type",
                    |m: &IndexReq| { &m.req_type },
                    |m: &mut IndexReq| { &mut m.req_type },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "peer_id",
                    |m: &IndexReq| { &m.peer_id },
                    |m: &mut IndexReq| { &mut m.peer_id },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "peer_addr",
                    |m: &IndexReq| { &m.peer_addr },
                    |m: &mut IndexReq| { &mut m.peer_addr },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "key",
                    |m: &IndexReq| { &m.key },
                    |m: &mut IndexReq| { &mut m.key },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "value",
                    |m: &IndexReq| { &m.value },
                    |m: &mut IndexReq| { &mut m.value },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "query",
                    |m: &IndexReq| { &m.query },
                    |m: &mut IndexReq| { &mut m.query },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<IndexReq>(
                    "IndexReq",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static IndexReq {
        static mut instance: ::protobuf::lazy::Lazy<IndexReq> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const IndexReq,
        };
        unsafe {
            instance.get(IndexReq::new)
        }
    }
}

impl ::protobuf::Clear for IndexReq {
    fn clear(&mut self) {
        self.client_id = 0;
        self.seq = 0;
        self.req_type = ReqType::Get;
        self.peer_id = 0;
        self.peer_addr.clear();
        self.key.clear();
        self.value.clear();
        self.query.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for IndexReq {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for IndexReq {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ConfChangeReq {
    // message fields
    pub cc: ::protobuf::SingularPtrField<super::eraftpb::ConfChange>,
    pub ip: ::std::string::String,
    pub port: u32,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ConfChangeReq {
    fn default() -> &'a ConfChangeReq {
        <ConfChangeReq as ::protobuf::Message>::default_instance()
    }
}

impl ConfChangeReq {
    pub fn new() -> ConfChangeReq {
        ::std::default::Default::default()
    }

    // .eraftpb.ConfChange cc = 1;


    pub fn get_cc(&self) -> &super::eraftpb::ConfChange {
        self.cc.as_ref().unwrap_or_else(|| super::eraftpb::ConfChange::default_instance())
    }
    pub fn clear_cc(&mut self) {
        self.cc.clear();
    }

    pub fn has_cc(&self) -> bool {
        self.cc.is_some()
    }

    // Param is passed by value, moved
    pub fn set_cc(&mut self, v: super::eraftpb::ConfChange) {
        self.cc = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_cc(&mut self) -> &mut super::eraftpb::ConfChange {
        if self.cc.is_none() {
            self.cc.set_default();
        }
        self.cc.as_mut().unwrap()
    }

    // Take field
    pub fn take_cc(&mut self) -> super::eraftpb::ConfChange {
        self.cc.take().unwrap_or_else(|| super::eraftpb::ConfChange::new())
    }

    // string ip = 2;


    pub fn get_ip(&self) -> &str {
        &self.ip
    }
    pub fn clear_ip(&mut self) {
        self.ip.clear();
    }

    // Param is passed by value, moved
    pub fn set_ip(&mut self, v: ::std::string::String) {
        self.ip = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_ip(&mut self) -> &mut ::std::string::String {
        &mut self.ip
    }

    // Take field
    pub fn take_ip(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.ip, ::std::string::String::new())
    }

    // uint32 port = 3;


    pub fn get_port(&self) -> u32 {
        self.port
    }
    pub fn clear_port(&mut self) {
        self.port = 0;
    }

    // Param is passed by value, moved
    pub fn set_port(&mut self, v: u32) {
        self.port = v;
    }
}

impl ::protobuf::Message for ConfChangeReq {
    fn is_initialized(&self) -> bool {
        for v in &self.cc {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.cc)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.ip)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.port = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.cc.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if !self.ip.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.ip);
        }
        if self.port != 0 {
            my_size += ::protobuf::rt::value_size(3, self.port, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.cc.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if !self.ip.is_empty() {
            os.write_string(2, &self.ip)?;
        }
        if self.port != 0 {
            os.write_uint32(3, self.port)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ConfChangeReq {
        ConfChangeReq::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::eraftpb::ConfChange>>(
                    "cc",
                    |m: &ConfChangeReq| { &m.cc },
                    |m: &mut ConfChangeReq| { &mut m.cc },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "ip",
                    |m: &ConfChangeReq| { &m.ip },
                    |m: &mut ConfChangeReq| { &mut m.ip },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "port",
                    |m: &ConfChangeReq| { &m.port },
                    |m: &mut ConfChangeReq| { &mut m.port },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ConfChangeReq>(
                    "ConfChangeReq",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ConfChangeReq {
        static mut instance: ::protobuf::lazy::Lazy<ConfChangeReq> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ConfChangeReq,
        };
        unsafe {
            instance.get(ConfChangeReq::new)
        }
    }
}

impl ::protobuf::Clear for ConfChangeReq {
    fn clear(&mut self) {
        self.cc.clear();
        self.ip.clear();
        self.port = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ConfChangeReq {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ConfChangeReq {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct GetResp {
    // message fields
    pub value: ::std::string::String,
    pub err: RespErr,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a GetResp {
    fn default() -> &'a GetResp {
        <GetResp as ::protobuf::Message>::default_instance()
    }
}

impl GetResp {
    pub fn new() -> GetResp {
        ::std::default::Default::default()
    }

    // string value = 1;


    pub fn get_value(&self) -> &str {
        &self.value
    }
    pub fn clear_value(&mut self) {
        self.value.clear();
    }

    // Param is passed by value, moved
    pub fn set_value(&mut self, v: ::std::string::String) {
        self.value = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_value(&mut self) -> &mut ::std::string::String {
        &mut self.value
    }

    // Take field
    pub fn take_value(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.value, ::std::string::String::new())
    }

    // .indexrpcpb.RespErr err = 2;


    pub fn get_err(&self) -> RespErr {
        self.err
    }
    pub fn clear_err(&mut self) {
        self.err = RespErr::OK;
    }

    // Param is passed by value, moved
    pub fn set_err(&mut self, v: RespErr) {
        self.err = v;
    }
}

impl ::protobuf::Message for GetResp {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.value)?;
                },
                2 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.err, 2, &mut self.unknown_fields)?
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.value.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.value);
        }
        if self.err != RespErr::OK {
            my_size += ::protobuf::rt::enum_size(2, self.err);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.value.is_empty() {
            os.write_string(1, &self.value)?;
        }
        if self.err != RespErr::OK {
            os.write_enum(2, self.err.value())?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> GetResp {
        GetResp::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "value",
                    |m: &GetResp| { &m.value },
                    |m: &mut GetResp| { &mut m.value },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<RespErr>>(
                    "err",
                    |m: &GetResp| { &m.err },
                    |m: &mut GetResp| { &mut m.err },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<GetResp>(
                    "GetResp",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static GetResp {
        static mut instance: ::protobuf::lazy::Lazy<GetResp> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const GetResp,
        };
        unsafe {
            instance.get(GetResp::new)
        }
    }
}

impl ::protobuf::Clear for GetResp {
    fn clear(&mut self) {
        self.value.clear();
        self.err = RespErr::OK;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for GetResp {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GetResp {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct PutResp {
    // message fields
    pub err: RespErr,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a PutResp {
    fn default() -> &'a PutResp {
        <PutResp as ::protobuf::Message>::default_instance()
    }
}

impl PutResp {
    pub fn new() -> PutResp {
        ::std::default::Default::default()
    }

    // .indexrpcpb.RespErr err = 1;


    pub fn get_err(&self) -> RespErr {
        self.err
    }
    pub fn clear_err(&mut self) {
        self.err = RespErr::OK;
    }

    // Param is passed by value, moved
    pub fn set_err(&mut self, v: RespErr) {
        self.err = v;
    }
}

impl ::protobuf::Message for PutResp {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.err, 1, &mut self.unknown_fields)?
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.err != RespErr::OK {
            my_size += ::protobuf::rt::enum_size(1, self.err);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.err != RespErr::OK {
            os.write_enum(1, self.err.value())?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> PutResp {
        PutResp::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<RespErr>>(
                    "err",
                    |m: &PutResp| { &m.err },
                    |m: &mut PutResp| { &mut m.err },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<PutResp>(
                    "PutResp",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static PutResp {
        static mut instance: ::protobuf::lazy::Lazy<PutResp> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const PutResp,
        };
        unsafe {
            instance.get(PutResp::new)
        }
    }
}

impl ::protobuf::Clear for PutResp {
    fn clear(&mut self) {
        self.err = RespErr::OK;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for PutResp {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PutResp {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct DeleteResp {
    // message fields
    pub err: RespErr,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a DeleteResp {
    fn default() -> &'a DeleteResp {
        <DeleteResp as ::protobuf::Message>::default_instance()
    }
}

impl DeleteResp {
    pub fn new() -> DeleteResp {
        ::std::default::Default::default()
    }

    // .indexrpcpb.RespErr err = 1;


    pub fn get_err(&self) -> RespErr {
        self.err
    }
    pub fn clear_err(&mut self) {
        self.err = RespErr::OK;
    }

    // Param is passed by value, moved
    pub fn set_err(&mut self, v: RespErr) {
        self.err = v;
    }
}

impl ::protobuf::Message for DeleteResp {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.err, 1, &mut self.unknown_fields)?
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.err != RespErr::OK {
            my_size += ::protobuf::rt::enum_size(1, self.err);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.err != RespErr::OK {
            os.write_enum(1, self.err.value())?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> DeleteResp {
        DeleteResp::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<RespErr>>(
                    "err",
                    |m: &DeleteResp| { &m.err },
                    |m: &mut DeleteResp| { &mut m.err },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<DeleteResp>(
                    "DeleteResp",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static DeleteResp {
        static mut instance: ::protobuf::lazy::Lazy<DeleteResp> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const DeleteResp,
        };
        unsafe {
            instance.get(DeleteResp::new)
        }
    }
}

impl ::protobuf::Clear for DeleteResp {
    fn clear(&mut self) {
        self.err = RespErr::OK;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for DeleteResp {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DeleteResp {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct SearchResp {
    // message fields
    pub value: ::std::string::String,
    pub err: RespErr,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a SearchResp {
    fn default() -> &'a SearchResp {
        <SearchResp as ::protobuf::Message>::default_instance()
    }
}

impl SearchResp {
    pub fn new() -> SearchResp {
        ::std::default::Default::default()
    }

    // string value = 1;


    pub fn get_value(&self) -> &str {
        &self.value
    }
    pub fn clear_value(&mut self) {
        self.value.clear();
    }

    // Param is passed by value, moved
    pub fn set_value(&mut self, v: ::std::string::String) {
        self.value = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_value(&mut self) -> &mut ::std::string::String {
        &mut self.value
    }

    // Take field
    pub fn take_value(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.value, ::std::string::String::new())
    }

    // .indexrpcpb.RespErr err = 2;


    pub fn get_err(&self) -> RespErr {
        self.err
    }
    pub fn clear_err(&mut self) {
        self.err = RespErr::OK;
    }

    // Param is passed by value, moved
    pub fn set_err(&mut self, v: RespErr) {
        self.err = v;
    }
}

impl ::protobuf::Message for SearchResp {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.value)?;
                },
                2 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.err, 2, &mut self.unknown_fields)?
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.value.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.value);
        }
        if self.err != RespErr::OK {
            my_size += ::protobuf::rt::enum_size(2, self.err);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.value.is_empty() {
            os.write_string(1, &self.value)?;
        }
        if self.err != RespErr::OK {
            os.write_enum(2, self.err.value())?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> SearchResp {
        SearchResp::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "value",
                    |m: &SearchResp| { &m.value },
                    |m: &mut SearchResp| { &mut m.value },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<RespErr>>(
                    "err",
                    |m: &SearchResp| { &m.err },
                    |m: &mut SearchResp| { &mut m.err },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<SearchResp>(
                    "SearchResp",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static SearchResp {
        static mut instance: ::protobuf::lazy::Lazy<SearchResp> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const SearchResp,
        };
        unsafe {
            instance.get(SearchResp::new)
        }
    }
}

impl ::protobuf::Clear for SearchResp {
    fn clear(&mut self) {
        self.value.clear();
        self.err = RespErr::OK;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for SearchResp {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SearchResp {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct RaftDone {
    // message fields
    pub err: RespErr,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a RaftDone {
    fn default() -> &'a RaftDone {
        <RaftDone as ::protobuf::Message>::default_instance()
    }
}

impl RaftDone {
    pub fn new() -> RaftDone {
        ::std::default::Default::default()
    }

    // .indexrpcpb.RespErr err = 1;


    pub fn get_err(&self) -> RespErr {
        self.err
    }
    pub fn clear_err(&mut self) {
        self.err = RespErr::OK;
    }

    // Param is passed by value, moved
    pub fn set_err(&mut self, v: RespErr) {
        self.err = v;
    }
}

impl ::protobuf::Message for RaftDone {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.err, 1, &mut self.unknown_fields)?
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.err != RespErr::OK {
            my_size += ::protobuf::rt::enum_size(1, self.err);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.err != RespErr::OK {
            os.write_enum(1, self.err.value())?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> RaftDone {
        RaftDone::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<RespErr>>(
                    "err",
                    |m: &RaftDone| { &m.err },
                    |m: &mut RaftDone| { &mut m.err },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<RaftDone>(
                    "RaftDone",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static RaftDone {
        static mut instance: ::protobuf::lazy::Lazy<RaftDone> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const RaftDone,
        };
        unsafe {
            instance.get(RaftDone::new)
        }
    }
}

impl ::protobuf::Clear for RaftDone {
    fn clear(&mut self) {
        self.err = RespErr::OK;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for RaftDone {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RaftDone {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum RespErr {
    OK = 0,
    ErrWrongLeader = 1,
    ErrNoKey = 2,
}

impl ::protobuf::ProtobufEnum for RespErr {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<RespErr> {
        match value {
            0 => ::std::option::Option::Some(RespErr::OK),
            1 => ::std::option::Option::Some(RespErr::ErrWrongLeader),
            2 => ::std::option::Option::Some(RespErr::ErrNoKey),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [RespErr] = &[
            RespErr::OK,
            RespErr::ErrWrongLeader,
            RespErr::ErrNoKey,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::EnumDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                ::protobuf::reflect::EnumDescriptor::new("RespErr", file_descriptor_proto())
            })
        }
    }
}

impl ::std::marker::Copy for RespErr {
}

impl ::std::default::Default for RespErr {
    fn default() -> Self {
        RespErr::OK
    }
}

impl ::protobuf::reflect::ProtobufValue for RespErr {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Enum(self.descriptor())
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum ReqType {
    Get = 0,
    Put = 1,
    Delete = 2,
    Search = 3,
    PeerAddr = 4,
}

impl ::protobuf::ProtobufEnum for ReqType {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<ReqType> {
        match value {
            0 => ::std::option::Option::Some(ReqType::Get),
            1 => ::std::option::Option::Some(ReqType::Put),
            2 => ::std::option::Option::Some(ReqType::Delete),
            3 => ::std::option::Option::Some(ReqType::Search),
            4 => ::std::option::Option::Some(ReqType::PeerAddr),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [ReqType] = &[
            ReqType::Get,
            ReqType::Put,
            ReqType::Delete,
            ReqType::Search,
            ReqType::PeerAddr,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::EnumDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                ::protobuf::reflect::EnumDescriptor::new("ReqType", file_descriptor_proto())
            })
        }
    }
}

impl ::std::marker::Copy for ReqType {
}

impl ::std::default::Default for ReqType {
    fn default() -> Self {
        ReqType::Get
    }
}

impl ::protobuf::reflect::ProtobufValue for ReqType {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Enum(self.descriptor())
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x10indexrpcpb.proto\x12\nindexrpcpb\x1a\reraftpb.proto\"\xdd\x01\n\
    \x08IndexReq\x12\x1b\n\tclient_id\x18\x01\x20\x01(\x04R\x08clientId\x12\
    \x10\n\x03seq\x18\x02\x20\x01(\x04R\x03seq\x12.\n\x08req_type\x18\x03\
    \x20\x01(\x0e2\x13.indexrpcpb.ReqTypeR\x07reqType\x12\x17\n\x07peer_id\
    \x18\x04\x20\x01(\x04R\x06peerId\x12\x1b\n\tpeer_addr\x18\x05\x20\x01(\t\
    R\x08peerAddr\x12\x10\n\x03key\x18\x06\x20\x01(\tR\x03key\x12\x14\n\x05v\
    alue\x18\x07\x20\x01(\tR\x05value\x12\x14\n\x05query\x18\x08\x20\x01(\tR\
    \x05query\"X\n\rConfChangeReq\x12#\n\x02cc\x18\x01\x20\x01(\x0b2\x13.era\
    ftpb.ConfChangeR\x02cc\x12\x0e\n\x02ip\x18\x02\x20\x01(\tR\x02ip\x12\x12\
    \n\x04port\x18\x03\x20\x01(\rR\x04port\"F\n\x07GetResp\x12\x14\n\x05valu\
    e\x18\x01\x20\x01(\tR\x05value\x12%\n\x03err\x18\x02\x20\x01(\x0e2\x13.i\
    ndexrpcpb.RespErrR\x03err\"0\n\x07PutResp\x12%\n\x03err\x18\x01\x20\x01(\
    \x0e2\x13.indexrpcpb.RespErrR\x03err\"3\n\nDeleteResp\x12%\n\x03err\x18\
    \x01\x20\x01(\x0e2\x13.indexrpcpb.RespErrR\x03err\"I\n\nSearchResp\x12\
    \x14\n\x05value\x18\x01\x20\x01(\tR\x05value\x12%\n\x03err\x18\x02\x20\
    \x01(\x0e2\x13.indexrpcpb.RespErrR\x03err\"1\n\x08RaftDone\x12%\n\x03err\
    \x18\x01\x20\x01(\x0e2\x13.indexrpcpb.RespErrR\x03err*3\n\x07RespErr\x12\
    \x06\n\x02OK\x10\0\x12\x12\n\x0eErrWrongLeader\x10\x01\x12\x0c\n\x08ErrN\
    oKey\x10\x02*A\n\x07ReqType\x12\x07\n\x03Get\x10\0\x12\x07\n\x03Put\x10\
    \x01\x12\n\n\x06Delete\x10\x02\x12\n\n\x06Search\x10\x03\x12\x0c\n\x08Pe\
    erAddr\x10\x04J\xb3\x0e\n\x06\x12\x04\0\08\x01\n\x08\n\x01\x0c\x12\x03\0\
    \0\x12\n\x08\n\x01\x02\x12\x03\x01\0\x13\n\t\n\x02\x03\0\x12\x03\x03\0\
    \x17\n\n\n\x02\x05\0\x12\x04\x05\0\t\x01\n\n\n\x03\x05\0\x01\x12\x03\x05\
    \x05\x0c\n\x0b\n\x04\x05\0\x02\0\x12\x03\x06\x04\x0b\n\x0c\n\x05\x05\0\
    \x02\0\x01\x12\x03\x06\x04\x06\n\x0c\n\x05\x05\0\x02\0\x02\x12\x03\x06\t\
    \n\n\x0b\n\x04\x05\0\x02\x01\x12\x03\x07\x04\x17\n\x0c\n\x05\x05\0\x02\
    \x01\x01\x12\x03\x07\x04\x12\n\x0c\n\x05\x05\0\x02\x01\x02\x12\x03\x07\
    \x15\x16\n\x0b\n\x04\x05\0\x02\x02\x12\x03\x08\x04\x11\n\x0c\n\x05\x05\0\
    \x02\x02\x01\x12\x03\x08\x04\x0c\n\x0c\n\x05\x05\0\x02\x02\x02\x12\x03\
    \x08\x0f\x10\n\n\n\x02\x05\x01\x12\x04\x0b\0\x11\x01\n\n\n\x03\x05\x01\
    \x01\x12\x03\x0b\x05\x0c\n\x0b\n\x04\x05\x01\x02\0\x12\x03\x0c\x04\x0c\n\
    \x0c\n\x05\x05\x01\x02\0\x01\x12\x03\x0c\x04\x07\n\x0c\n\x05\x05\x01\x02\
    \0\x02\x12\x03\x0c\n\x0b\n\x0b\n\x04\x05\x01\x02\x01\x12\x03\r\x04\x0c\n\
    \x0c\n\x05\x05\x01\x02\x01\x01\x12\x03\r\x04\x07\n\x0c\n\x05\x05\x01\x02\
    \x01\x02\x12\x03\r\n\x0b\n\x0b\n\x04\x05\x01\x02\x02\x12\x03\x0e\x04\x0f\
    \n\x0c\n\x05\x05\x01\x02\x02\x01\x12\x03\x0e\x04\n\n\x0c\n\x05\x05\x01\
    \x02\x02\x02\x12\x03\x0e\r\x0e\n\x0b\n\x04\x05\x01\x02\x03\x12\x03\x0f\
    \x04\x0f\n\x0c\n\x05\x05\x01\x02\x03\x01\x12\x03\x0f\x04\n\n\x0c\n\x05\
    \x05\x01\x02\x03\x02\x12\x03\x0f\r\x0e\n\x0b\n\x04\x05\x01\x02\x04\x12\
    \x03\x10\x04\x11\n\x0c\n\x05\x05\x01\x02\x04\x01\x12\x03\x10\x04\x0c\n\
    \x0c\n\x05\x05\x01\x02\x04\x02\x12\x03\x10\x0f\x10\n\n\n\x02\x04\0\x12\
    \x04\x13\0\x1c\x01\n\n\n\x03\x04\0\x01\x12\x03\x13\x08\x10\n\x0b\n\x04\
    \x04\0\x02\0\x12\x03\x14\x04\x19\n\r\n\x05\x04\0\x02\0\x04\x12\x04\x14\
    \x04\x13\x12\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\x14\x04\n\n\x0c\n\x05\
    \x04\0\x02\0\x01\x12\x03\x14\x0b\x14\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\
    \x14\x17\x18\n\x0b\n\x04\x04\0\x02\x01\x12\x03\x15\x04\x13\n\r\n\x05\x04\
    \0\x02\x01\x04\x12\x04\x15\x04\x14\x19\n\x0c\n\x05\x04\0\x02\x01\x05\x12\
    \x03\x15\x04\n\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\x15\x0b\x0e\n\x0c\n\
    \x05\x04\0\x02\x01\x03\x12\x03\x15\x11\x12\n\x0b\n\x04\x04\0\x02\x02\x12\
    \x03\x16\x04\x19\n\r\n\x05\x04\0\x02\x02\x04\x12\x04\x16\x04\x15\x13\n\
    \x0c\n\x05\x04\0\x02\x02\x06\x12\x03\x16\x04\x0b\n\x0c\n\x05\x04\0\x02\
    \x02\x01\x12\x03\x16\x0c\x14\n\x0c\n\x05\x04\0\x02\x02\x03\x12\x03\x16\
    \x17\x18\n\x0b\n\x04\x04\0\x02\x03\x12\x03\x17\x04\x17\n\r\n\x05\x04\0\
    \x02\x03\x04\x12\x04\x17\x04\x16\x19\n\x0c\n\x05\x04\0\x02\x03\x05\x12\
    \x03\x17\x04\n\n\x0c\n\x05\x04\0\x02\x03\x01\x12\x03\x17\x0b\x12\n\x0c\n\
    \x05\x04\0\x02\x03\x03\x12\x03\x17\x15\x16\n\x0b\n\x04\x04\0\x02\x04\x12\
    \x03\x18\x04\x19\n\r\n\x05\x04\0\x02\x04\x04\x12\x04\x18\x04\x17\x17\n\
    \x0c\n\x05\x04\0\x02\x04\x05\x12\x03\x18\x04\n\n\x0c\n\x05\x04\0\x02\x04\
    \x01\x12\x03\x18\x0b\x14\n\x0c\n\x05\x04\0\x02\x04\x03\x12\x03\x18\x17\
    \x18\n\x0b\n\x04\x04\0\x02\x05\x12\x03\x19\x04\x13\n\r\n\x05\x04\0\x02\
    \x05\x04\x12\x04\x19\x04\x18\x19\n\x0c\n\x05\x04\0\x02\x05\x05\x12\x03\
    \x19\x04\n\n\x0c\n\x05\x04\0\x02\x05\x01\x12\x03\x19\x0b\x0e\n\x0c\n\x05\
    \x04\0\x02\x05\x03\x12\x03\x19\x11\x12\n\x0b\n\x04\x04\0\x02\x06\x12\x03\
    \x1a\x04\x15\n\r\n\x05\x04\0\x02\x06\x04\x12\x04\x1a\x04\x19\x13\n\x0c\n\
    \x05\x04\0\x02\x06\x05\x12\x03\x1a\x04\n\n\x0c\n\x05\x04\0\x02\x06\x01\
    \x12\x03\x1a\x0b\x10\n\x0c\n\x05\x04\0\x02\x06\x03\x12\x03\x1a\x13\x14\n\
    \x0b\n\x04\x04\0\x02\x07\x12\x03\x1b\x04\x15\n\r\n\x05\x04\0\x02\x07\x04\
    \x12\x04\x1b\x04\x1a\x15\n\x0c\n\x05\x04\0\x02\x07\x05\x12\x03\x1b\x04\n\
    \n\x0c\n\x05\x04\0\x02\x07\x01\x12\x03\x1b\x0b\x10\n\x0c\n\x05\x04\0\x02\
    \x07\x03\x12\x03\x1b\x13\x14\n\n\n\x02\x04\x01\x12\x04\x1e\0\"\x01\n\n\n\
    \x03\x04\x01\x01\x12\x03\x1e\x08\x15\n\x0b\n\x04\x04\x01\x02\0\x12\x03\
    \x1f\x04\x1e\n\r\n\x05\x04\x01\x02\0\x04\x12\x04\x1f\x04\x1e\x17\n\x0c\n\
    \x05\x04\x01\x02\0\x06\x12\x03\x1f\x04\x16\n\x0c\n\x05\x04\x01\x02\0\x01\
    \x12\x03\x1f\x17\x19\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03\x1f\x1c\x1d\n\
    \x0b\n\x04\x04\x01\x02\x01\x12\x03\x20\x04\x12\n\r\n\x05\x04\x01\x02\x01\
    \x04\x12\x04\x20\x04\x1f\x1e\n\x0c\n\x05\x04\x01\x02\x01\x05\x12\x03\x20\
    \x04\n\n\x0c\n\x05\x04\x01\x02\x01\x01\x12\x03\x20\x0b\r\n\x0c\n\x05\x04\
    \x01\x02\x01\x03\x12\x03\x20\x10\x11\n\x0b\n\x04\x04\x01\x02\x02\x12\x03\
    !\x04\x14\n\r\n\x05\x04\x01\x02\x02\x04\x12\x04!\x04\x20\x12\n\x0c\n\x05\
    \x04\x01\x02\x02\x05\x12\x03!\x04\n\n\x0c\n\x05\x04\x01\x02\x02\x01\x12\
    \x03!\x0b\x0f\n\x0c\n\x05\x04\x01\x02\x02\x03\x12\x03!\x12\x13\n\n\n\x02\
    \x04\x02\x12\x04$\0'\x01\n\n\n\x03\x04\x02\x01\x12\x03$\x08\x0f\n\x0b\n\
    \x04\x04\x02\x02\0\x12\x03%\x04\x15\n\r\n\x05\x04\x02\x02\0\x04\x12\x04%\
    \x04$\x11\n\x0c\n\x05\x04\x02\x02\0\x05\x12\x03%\x04\n\n\x0c\n\x05\x04\
    \x02\x02\0\x01\x12\x03%\x0b\x10\n\x0c\n\x05\x04\x02\x02\0\x03\x12\x03%\
    \x13\x14\n\x0b\n\x04\x04\x02\x02\x01\x12\x03&\x04\x14\n\r\n\x05\x04\x02\
    \x02\x01\x04\x12\x04&\x04%\x15\n\x0c\n\x05\x04\x02\x02\x01\x06\x12\x03&\
    \x04\x0b\n\x0c\n\x05\x04\x02\x02\x01\x01\x12\x03&\x0c\x0f\n\x0c\n\x05\
    \x04\x02\x02\x01\x03\x12\x03&\x12\x13\n\n\n\x02\x04\x03\x12\x04)\0+\x01\
    \n\n\n\x03\x04\x03\x01\x12\x03)\x08\x0f\n\x0b\n\x04\x04\x03\x02\0\x12\
    \x03*\x04\x14\n\r\n\x05\x04\x03\x02\0\x04\x12\x04*\x04)\x11\n\x0c\n\x05\
    \x04\x03\x02\0\x06\x12\x03*\x04\x0b\n\x0c\n\x05\x04\x03\x02\0\x01\x12\
    \x03*\x0c\x0f\n\x0c\n\x05\x04\x03\x02\0\x03\x12\x03*\x12\x13\n\n\n\x02\
    \x04\x04\x12\x04-\0/\x01\n\n\n\x03\x04\x04\x01\x12\x03-\x08\x12\n\x0b\n\
    \x04\x04\x04\x02\0\x12\x03.\x04\x14\n\r\n\x05\x04\x04\x02\0\x04\x12\x04.\
    \x04-\x14\n\x0c\n\x05\x04\x04\x02\0\x06\x12\x03.\x04\x0b\n\x0c\n\x05\x04\
    \x04\x02\0\x01\x12\x03.\x0c\x0f\n\x0c\n\x05\x04\x04\x02\0\x03\x12\x03.\
    \x12\x13\n\n\n\x02\x04\x05\x12\x041\04\x01\n\n\n\x03\x04\x05\x01\x12\x03\
    1\x08\x12\n\x0b\n\x04\x04\x05\x02\0\x12\x032\x04\x15\n\r\n\x05\x04\x05\
    \x02\0\x04\x12\x042\x041\x14\n\x0c\n\x05\x04\x05\x02\0\x05\x12\x032\x04\
    \n\n\x0c\n\x05\x04\x05\x02\0\x01\x12\x032\x0b\x10\n\x0c\n\x05\x04\x05\
    \x02\0\x03\x12\x032\x13\x14\n\x0b\n\x04\x04\x05\x02\x01\x12\x033\x04\x14\
    \n\r\n\x05\x04\x05\x02\x01\x04\x12\x043\x042\x15\n\x0c\n\x05\x04\x05\x02\
    \x01\x06\x12\x033\x04\x0b\n\x0c\n\x05\x04\x05\x02\x01\x01\x12\x033\x0c\
    \x0f\n\x0c\n\x05\x04\x05\x02\x01\x03\x12\x033\x12\x13\n\n\n\x02\x04\x06\
    \x12\x046\08\x01\n\n\n\x03\x04\x06\x01\x12\x036\x08\x10\n\x0b\n\x04\x04\
    \x06\x02\0\x12\x037\x04\x14\n\r\n\x05\x04\x06\x02\0\x04\x12\x047\x046\
    \x12\n\x0c\n\x05\x04\x06\x02\0\x06\x12\x037\x04\x0b\n\x0c\n\x05\x04\x06\
    \x02\0\x01\x12\x037\x0c\x0f\n\x0c\n\x05\x04\x06\x02\0\x03\x12\x037\x12\
    \x13b\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
